"""
Fichier de migration généré automatiquement par Django

Ce module définit les opérations de migration pour l'application
"""

# Generated by Django 3.0 on 2025-12-17 21:19

from django.db import migrations


class Migration(migrations.Migration):
    """
    Classe de migration.

    Attributes:
        dependencies (list): Dépendances de migration non existente ici
        operations (list): Liste des opérations de création de modèles
    """
    dependencies = [
        ('lettings', '0002_copy_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name': 'Letting', 'verbose_name_plural': 'Lettings'},
        ),
    ]
