"""
Migration auto-générée par Django

Cette migration supprime :
- le champ address du modèle Letting
- le modèle Address
- le modèle Letting
"""

# Generated by Django 3.0 on 2025-12-14 10:01

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration supprimant les modèles Address et Letting
    ainsi que le champ address de Letting
    """

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
    ]
