# Generated by Django 3.0 on 2025-12-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20251214_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
